export const MESSAGE_TYPES = {
  AUTH: 'AUTH',
  USER_ONLINE: 'USER_ONLINE',
  USER_OFFLINE: 'USER_OFFLINE',
  SEND_MESSAGE: 'SEND_MESSAGE',
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  MESSAGE_DELIVERED: 'MESSAGE_DELIVERED',
  MESSAGE_READ: 'MESSAGE_READ',
  KEY_BUNDLE_REQUEST: 'KEY_BUNDLE_REQUEST',
  KEY_BUNDLE_RESPONSE: 'KEY_BUNDLE_RESPONSE',
  TYPING_START: 'TYPING_START',
  TYPING_STOP: 'TYPING_STOP',
  ENCRYPTED_MESSAGE: 'encrypted_message'
};

export const PROTOCOL_VERSIONS = {
  SIGNAL_DEMO: 'v1'
};
